version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ../backend
    container_name: fastapi_app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ../backend:/app
    command: >
      sh -c "alembic revision --autogenerate && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  frontend:
    build: ../frontend
    container_name: react_app
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    depends_on:
      - frontend
    volumes:
      - ../frontend/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  postgres_data: